FROM maven:3.9-eclipse-temurin-21

WORKDIR /app

# copia tudo (pom.xml + src/)
COPY . .

# compila sem rodar testes
RUN mvn -q -DskipTests package

# roda o jar gerado pelo maven-shade-plugin (target/app.jar)
CMD ["java", "-jar", "target/app.jar"]
